- go.mod
- go.sum
> update go.mod to server v0.1.0

- examples/cars/scripts/carDemoGen.sh
Added script that creates all missing configuration files and folders - scripts/carDemoGen.sh
If you want to update configuration to have missing files and folders for cars demo, after you created docker image, you should run: 
```
./scripts/carDemoGen.sh <path to bcdb-server>/sampleconfig
``` 
To run car demo, you should start docker container created by `make docker` by:
```
docker run -it --rm -v <path to bcdb-server>/sampleconfig/:/etc/bcdb-server bcdb-server
```
update `CARS_DEMO_DIR`:
```
export CARS_DEMO_DIR=<path to bcdb-server>/sampleconfig
```
and run car demo starting from `./cars init` step 
> Updating cars demo to work with bcdb docker image

- examples/api/user_tx/user_tx.go
> user transaction example - add comment

- examples/api/db_tx/config.go
- examples/api/db_tx/config.yml
- examples/api/db_tx/db_tx.go
> database transaction example

- examples/api/README.md
> adding readme file to examples/api

- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/tx_context.go
- pkg/bcdb/tx_context_test.go
> Adding validity check to commit

- examples/api/provenance/provenance.go
> Example of using Provenance API

- examples/api/tx_validity/tx_validity.go
> Example that checks transaction validity

- examples/api/async_commit/async_commit.go
> Example of using async commit

- examples/api/acl_violation/acl_violation.go
> Example of non-valid transaction because of ACL violation

- LICENSE
> include Apache License 2.0

- examples/cars/commands/generate.go
> Missing config parameters in generate

- examples/api/acl_violation/acl_violation.go
- examples/api/async_commit/async_commit.go
- examples/api/db_tx/db_tx.go
- examples/api/insert_put_diff/insert_put_diff.go
- examples/api/provenance/provenance.go
- examples/api/simple_tx/simple_tx.go
- examples/api/state_proof/state_proof.go
- examples/api/tx_validity/tx_validity.go
- examples/api/user_tx/user_tx.go
> Change examples main

- go.mod
- go.sum
- pkg/bcdb/block_header_delivery.go
- pkg/bcdb/block_header_delivery_test.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/db.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/ledger.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/tx_context.go
- pkg/bcdb/user_tx_context_test.go
> augmented block header delivery service

- pkg/bcdb/ledger.go
- pkg/bcdb/tx_context.go
> Adding ErrorNotFound to distinguish between 404 and another errors

- examples/api/json_query/json_query.go
- examples/api/json_query/json_query_test.go
> Adding json query example

- go.mod
- go.sum
> update server version

- examples/api/acl_violation/acl_violation.go
- examples/api/acl_violation/acl_violation_test.go
- examples/api/async_commit/async_commit.go
- examples/api/async_commit/async_commit_test.go
- examples/api/db_tx/db_tx.go
- examples/api/db_tx/db_tx_test.go
- examples/api/insert_put_diff/insert_put_diff.go
- examples/api/insert_put_diff/insert_put_diff_test.go
- examples/api/multi_sign/multi_sign.go
- examples/api/multi_sign/multi_sign_test.go
- examples/api/provenance/provenance.go
- examples/api/provenance/provenance_test.go
- examples/api/simple_tx/simple_tx.go
- examples/api/simple_tx/simple_tx_test.go
- examples/api/tx_validity/tx_validity.go
- examples/api/tx_validity/tx_validity_test.go
- examples/api/user_tx/user_tx.go
- examples/api/user_tx/user_tx_test.go
- examples/util/testutil.go
> Examples unit tests

- examples/academic-docs/README.md
- examples/academic-docs/create-dbs-users/create-dbs-users.go
- examples/academic-docs/prepare-data/prepare-data.go
- examples/academic-docs/proof-and-verification/proof-and-verification.go
- examples/academic-docs/util/util.go
> demo: academic doc management

- examples/api/async_commit/async_commit_test.go
- examples/api/db_tx/db_tx_test.go
- examples/api/insert_put_diff/insert_put_diff_test.go
- examples/api/json_query/json_query_test.go
- examples/api/multi_sign/multi_sign_test.go
- examples/api/provenance/provenance_test.go
- examples/api/simple_tx/simple_tx_test.go
- examples/api/state_proof/state_proof_test.go
- examples/api/tx_validity/tx_validity_test.go
- examples/api/user_tx/user_tx_test.go
> change examples unit tests ports

- examples/api/README.md
- examples/util/config.yml
Added documentation about docker image volumes and new location of crypto.
> Docker docs update 

- examples/academic-docs/create-dbs-users/create-dbs-users.go
- examples/academic-docs/prepare-data/prepare-data.go
- examples/api/acl_violation/acl_violation.go
- examples/api/async_commit/async_commit.go
- examples/api/state_proof/state_proof.go
- examples/api/tx_validity/tx_validity.go
- examples/cars/commands/init.go
- examples/cars/commands/mint.go
- examples/cars/commands/transafer.go
- pkg/bcdb/config_tx_context.go
- pkg/bcdb/config_tx_context_test.go
- pkg/bcdb/data_tx_context.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/db.go
- pkg/bcdb/dbs_tx_context.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/json_query_test.go
- pkg/bcdb/loaded_data_tx_context.go
- pkg/bcdb/loaded_data_tx_context_test.go
- pkg/bcdb/provenance_test.go
- pkg/bcdb/tx_context.go
- pkg/bcdb/tx_context_test.go
- pkg/bcdb/user_tx_context.go
- pkg/bcdb/util_test.go
> Adding TxReceiptResponseEnvelope to commit return values

- examples/cars/commands/generate.go
- examples/cars/commands/init_test.go
- examples/util/testutil.go
- go.mod
- go.sum
- pkg/bcdb/util_test.go
Bump server version and apply change to code.
> Apply server API change Nodes: []config.NodeConf => []*config.NodeConf

- examples/cars/README.md
- examples/cars/commands/generate.go
- examples/cars/commands/init.go
- examples/cars/commands/list.go
- examples/cars/commands/mint.go
- examples/cars/commands/records.go
- examples/cars/commands/transafer.go
- examples/cars/commands/transfer_test.go
- examples/cars/commands/verify.go
- examples/cars/main.go
- examples/cars/main_test.go
> Augment cars demo with multi-sig and proofs

- pkg/bcdb/db.go
- pkg/bcdb/ledger.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/proof.go
- pkg/bcdb/user_tx_context.go
> Added utility to verify ledger path proof

- pkg/bcdb/block_header_delivery_test.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/db.go
- pkg/bcdb/ledger.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/proof.go
Added utility to verify all tx proof parts - merkle tree and ledger connectivity
> Full tx proof

- examples/cars/main_test.go
- go.mod
- go.sum
- pkg/bcdb/block_header_delivery_test.go
- pkg/bcdb/config_tx_context_test.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/json_query_test.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/loaded_data_tx_context_test.go
- pkg/bcdb/provenance_test.go
- pkg/bcdb/user_tx_context_test.go
> Update server version to v0.2.2

- go.mod
- go.sum
- pkg/bcdb/config_tx_context_test.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/db.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/provenance_test.go
- pkg/bcdb/session.go
- pkg/bcdb/tls_test.go
- pkg/bcdb/user_tx_context_test.go
- pkg/bcdb/util_test.go
- pkg/config/config.go
1. Support for server side tls
2. Support for both server and client tls
> TLS support

- pkg/bcdb/dbs_tx_context_test.go
Check creating the same DB twice.
> Improve DB create unit test

- pkg/bcdb/config_tx_context_test.go
> test - add user admin

- examples/cars/commands/utils.go
- go.mod
- go.sum
- pkg/bcdb/block_header_delivery.go
- pkg/bcdb/block_header_delivery_test.go
- pkg/bcdb/config_tx_context.go
- pkg/bcdb/data_query_test.go
- pkg/bcdb/data_tx_context.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/db.go
- pkg/bcdb/dbs_tx_context.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/ledger.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/loaded_data_tx_context.go
- pkg/bcdb/loaded_data_tx_context_test.go
- pkg/bcdb/mocks/rest_client.go
- pkg/bcdb/proof.go
- pkg/bcdb/provenance_test.go
- pkg/bcdb/rest_client.go
- pkg/bcdb/session.go
- pkg/bcdb/tls_test.go
- pkg/bcdb/tx_context.go
- pkg/bcdb/user_tx_context.go
- pkg/bcdb/user_tx_context_test.go
- pkg/bcdb/util_test.go
> replace json marshalling with protojson

- pkg/bcdb/config_tx_context_test.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/db.go
- pkg/bcdb/dbs_tx_context_test.go
- pkg/bcdb/tx_context.go
Signed-off-by: May Rosenbaum <mayro1595@gmail.com>
> exspose TxID

- go.mod
- go.sum
> server version v0.2.7

- examples/academic-docs/proof-and-verification/proof-and-verification.go
- examples/api/state_proof/state_proof.go
- examples/cars/commands/verify.go
- go.mod
- go.sum
- pkg/bcdb/ledger_test.go
- pkg/bcdb/proof.go
> fix merkle typo in server

- examples/api/user_tx/user_tx.go
- pkg/bcdb/config_tx_context_test.go
- pkg/bcdb/data_tx_context_test.go
- pkg/bcdb/user_tx_context.go
- pkg/bcdb/user_tx_context_test.go
- pkg/bcdb/util_test.go
Signed-off-by: May Rosenbaum <mayro1595@gmail.com>
> getUser return ACL

- go.mod
- go.sum
- pkg/bcdb/db.go
- pkg/bcdb/ledger.go
- pkg/bcdb/ledger_test.go
- pkg/bcdb/tx_context.go
> Expose API to get the TX content

- go.mod
- go.sum
> Bump server version v0.2.8

- pkg/bcdb/user_tx_context_test.go
Signed-off-by: May Rosenbaum <mayro1595@gmail.com>
> Test user ACL
